### ISSUE TITLE
Lists bullets overlaps floated image untill page resized

### ISSUE THREAD

**Issue by paulradzkov** [paulradzkov/bettertext.css#4]
<img width="2004" alt="codepen - a pen by paul radzkov 2017-06-10 23-00-21" src="https://user-images.githubusercontent.com/475929/27005915-e61fa0ba-4e30-11e7-92fb-e56d08412483.png">

On first load and when cache disabled bullets overlaps floated image.

**Comment by paulradzkov** [comment]
Added invisible animation to trigger recalculation on page load:

```less
    /* lists without classes */

    // 1) force reflow to fix bullet overlapping.
    // See https://git.io/vHyUo for details.

    ul:not([class]),
    ol:not([class]) {
        margin: 0 0 @m-default;
        max-width: calc(@linel - 2.5em);
        padding-left: 0;
        padding-right: 2.5em;

        ul,
        ol {
            margin-bottom: 0;
        }

        li {
            transform: translateX(2.5em);
            animation: fixlists 1s; // 1)
        }
    }

    @keyframes fixlists {
        0%   { text-indent: -0.001em;}
        100% { text-indent: 0;}
    }
```
